var annotated_dup =
[
    [ "AbstractSocketCommunicator", "class_abstract_socket_communicator.html", "class_abstract_socket_communicator" ],
    [ "Arduino", "class_arduino.html", "class_arduino" ],
    [ "ConfigProcessor", "class_config_processor.html", "class_config_processor" ],
    [ "daq_failure", "classdaq__failure.html", "classdaq__failure" ],
    [ "data_triple", "structdata__triple.html", "structdata__triple" ],
    [ "ExperimentParameters", "class_experiment_parameters.html", "class_experiment_parameters" ],
    [ "FlatFileSaver", "class_flat_file_saver.html", "class_flat_file_saver" ],
    [ "FrequencyControls", "class_frequency_controls.html", "class_frequency_controls" ],
    [ "MainWindow", "class_main_window.html", "class_main_window" ],
    [ "mode_track_failure", "classmode__track__failure.html", "classmode__track__failure" ],
    [ "ModeTrack", "class_mode_track.html", "class_mode_track" ],
    [ "ModeTraits", "class_mode_traits.html", "class_mode_traits" ],
    [ "NetworkAnalyzer", "class_network_analyzer.html", "class_network_analyzer" ],
    [ "PlainDataParam", "struct_plain_data_param.html", "struct_plain_data_param" ],
    [ "PowerControls", "class_power_controls.html", "class_power_controls" ],
    [ "Program", "class_program.html", "class_program" ],
    [ "ProgramCore", "class_program_core.html", "class_program_core" ],
    [ "ProgramFrame", "class_program_frame.html", "class_program_frame" ],
    [ "QSocketComm", "class_q_socket_comm.html", "class_q_socket_comm" ],
    [ "RetrieveVal", "struct_retrieve_val.html", "struct_retrieve_val" ],
    [ "RightClickMenu", "class_right_click_menu.html", "class_right_click_menu" ],
    [ "SignalGenerator", "class_signal_generator.html", "class_signal_generator" ],
    [ "SocketComm", "class_socket_comm.html", "class_socket_comm" ],
    [ "SpectrumAnalyzer", "class_spectrum_analyzer.html", "class_spectrum_analyzer" ],
    [ "StepperMotor", "class_stepper_motor.html", "class_stepper_motor" ],
    [ "Switch", "class_switch.html", "class_switch" ],
    [ "TCPSocketParam", "struct_t_c_p_socket_param.html", "struct_t_c_p_socket_param" ],
    [ "TestConfigProcessor", "class_test_config_processor.html", "class_test_config_processor" ],
    [ "VoltsTodBm_FFTCorrection", "struct_volts_tod_bm___f_f_t_correction.html", "struct_volts_tod_bm___f_f_t_correction" ]
];